server:
  port: 80
  # 应用的上下文路径，也可以称为项目路径，是构成url地址的一部分
  # 此时的访问方式为localhost:8088/community/xxxxxx
  servlet:
    context-path: /community

Community:
  path:
    domain: http://127.0.0.1:80
    upload: E:\一大堆\Java\社区网站\upload

spring:

  # Thymeleaf 模板缓存
  thymeleaf:
    cache: false

  # Redis
  redis:
    # 可用数据库数量
    # 数据库是由一个整数索引标识，而不是由一个数据库名称，可以直白的理解为配置不同的的库，占用的是不同的内存空间，
    # 不同的库之间相互不影响，独立工作，只不过都是借宿在这个Redis实例上面生存的空间。
    database: 0
    host: localhost
    port: 6379

  # Kafka
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: community-consumer-group
      #自动提交
      enable-auto-commit: true
      auto-commit-interval: 3000

  # DataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000

  # Mail
  mail:
    host: smtp.qq.com
    port: 465
    username: 1067550651@qq.com
    password: zjnvhzigxilebchb
    protocol: smtps
    default-encoding: UTF-8
  banner:
    charset: UTF-8

# Mybatis
mybatis:
  configuration:
    # 自动转驼峰
    map-underscore-to-camel-case: true
    # 允许JDBC支持自动生成主键，需要驱动兼容
    use-generated-keys: true
    # 控制台标准日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

