server:
  port: 80
  # 应用的上下文路径，也可以称为项目路径，是构成url地址的一部分
  # 此时的访问方式为localhost:8088/community/xxxxxx
  servlet:
    context-path: /community

Community:
  path:
    domain: http://127.0.0.1:80
    upload: E:\一大堆\Java\社区网站\upload

spring:

  # Thymeleaf 模板缓存
  thymeleaf:
    cache: false

  # Redis
  redis:
    # 可用数据库数量
    # 数据库是由一个整数索引标识，而不是由一个数据库名称，可以直白的理解为配置不同的的库，占用的是不同的内存空间，
    # 不同的库之间相互不影响，独立工作，只不过都是借宿在这个Redis实例上面生存的空间。
    database: 0
    host: localhost
    port: 6379

  # Kafka
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: consumer-group
      #自动提交
      enable-auto-commit: true
      auto-commit-interval: 3000

  # DataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000

  # Elasticsearch
  elasticsearch:
    uris: 127.0.0.1:9200
    connection-timeout: 1s
    socket-timeout: 30s

  # Spring线程池
  task:
    execution:
      pool:
        core-size: 8
        max-size: 15
        queue-capacity: 100
    scheduling:
      pool:
        size: 5

  # quartz
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            #持久化方式，默认存储在内存中，此处使用数据库方式
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            #需要为JobStore选择一个DriverDelegate才能使用。DriverDelegate负责执行特定数据库可能需要的任何JDBC工作
            # StdJDBCDelegate是一个使用“vanilla”JDBC代码（和SQL语句）来执行其工作的委托,用于完全符合JDBC的驱动程序
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            #设置为“true”以打开群集功能。如果有多个Quartz实例使用同一组数据库表，则此属性必须设置为“true”，否则您将遇到破坏
            isClustered: true
          threadPool:
            #实例化ThreadPool时，使用的线程类为SimpleThreadPool
            class: org.quartz.simpl.SimpleThreadPool
            #只有1到100之间的数字是非常实用的
            threadCount: 5

  # Mail
  mail:
    host: smtp.qq.com
    port: 465
    username: 1067550651@qq.com
    password: zjnvhzigxilebchb
    protocol: smtps
    default-encoding: UTF-8
  banner:
    charset: UTF-8

  # caffeine
  cache:
    type: caffeine
#    # 缓存最大数量和过期时间
#    caffeine:
#      spec: maximumSize=15,expireAfterWrite=180s
# 已在DiscussPostService代码中配置如下属性max-size expire-seconds

# @Value属性值注入
caffeine:
  posts:
    max-size: 15
    expire-seconds: 180

# Mybatis
mybatis:
  configuration:
    # 自动转驼峰
    map-underscore-to-camel-case: true
    # 允许JDBC支持自动生成主键，需要驱动兼容
    use-generated-keys: true
    # 控制台标准日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

